//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallTalk.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> MentorId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<System.DateTime> MeetingTime { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<bool> IsLessonOpened { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> StudentHasApproved { get; set; }
        public Nullable<bool> MentorHasApproved { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual Profile Profile1 { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual LessonRating LessonRating { get; set; }
    }
}
