//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallTalk.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationPreference
    {
        public int id { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> ProfileId { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
