//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallTalk.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmallTalkEntities : DbContext
    {
        public SmallTalkEntities()
            : base("name=SmallTalkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LanguageLevel> LanguageLevels { get; set; }
        public virtual DbSet<Lesson> Lessons { get; set; }
        public virtual DbSet<LessonRating> LessonRatings { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<StudentProgress> StudentProgresses { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<LocationPreference> LocationPreferences { get; set; }
        public virtual DbSet<ProfileLessonAvailability> ProfileLessonAvailabilities { get; set; }
    }
}
