//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallTalk.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentProgress
    {
        public int id { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> LessonId { get; set; }
        public Nullable<System.DateTime> StudyDate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> ProfileId { get; set; }
    
        public virtual Unit Unit { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
